const express=require('express');
const cors=require('cors');
const auth=require('./routes/auth');
const tasks=require('./routes/tasks');
const app=express();
app.use(cors());
app.use(express.json());
app.use('/auth',auth);
app.use('/tasks',tasks);
app.get('/',(req,res)=>res.send({ok:true}));
module.exports=app;